#!/usr/bin/env python3
"""
Injects canonical + Open Graph + Twitter Card + JSON-LD into every page.

    python3 scripts/build_seo.py --dry-run
    python3 scripts/build_seo.py

IDEMPOTENT. Everything it writes lives between the markers

    <!-- SEO:BEGIN (generated by scripts/build_seo.py — do not edit by hand) -->
    <!-- SEO:END -->

so re-running replaces that block rather than appending a second copy. Edit this
script, never the block. Anything outside the markers is left untouched, which is
what lets it run safely against 71KB of hand-written homepage.

Prices, URLs and identity all come from scripts/seo_config.py. Structured data that
disagrees with the visible page is a penalty risk, so the offers in the schema are
the same constants the pricing section renders from.
"""
import argparse
import html as H
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import seo_config as C  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEGIN = "<!-- SEO:BEGIN (generated by scripts/build_seo.py — do not edit by hand) -->"
END = "<!-- SEO:END -->"

# ---------------------------------------------------------------------------
# Per-page metadata.
#
# Titles <= 60 chars and descriptions <= 155 chars, because Google truncates past
# roughly that and a truncated title is a wasted title.
#
# The homepage title previously read "Toolbelt - The #1 Invoice App for
# Contractors". "#1" is a claim we cannot substantiate — there is no ranking, no
# award, and no source. It is also a weak title for search: it spends its first
# and most valuable characters on the brand name and a boast rather than on the
# phrase people actually type. Replaced with the keyword first, brand last.
# ---------------------------------------------------------------------------
PAGES = {
    "index.html": {
        "title": "Invoice App for Contractors | Toolbelt",
        "desc": ("Create invoices and quotes from the job site in seconds. Voice input, "
                 "AI descriptions, works offline. Free for 3 documents a month. iPhone."),
        "path": "/",
        "og_type": "website",
    },
    "blog/index.html": {
        "title": "Contractor Invoicing Blog | Toolbelt",
        "desc": ("Practical guides on invoicing, quoting and getting paid faster as a "
                 "contractor — written for people who bill from the truck, not a desk."),
        "path": "/blog/",
        "og_type": "website",
    },
    "support.html": {
        "title": "Support & Help | Toolbelt Invoice App",
        "desc": ("Get help with Toolbelt: invoices, quotes, subscriptions, offline mode "
                 "and data. Answers to common questions, plus how to reach a human."),
        "path": "/support.html",
        "og_type": "website",
    },
    "privacy.html": {
        "title": "Privacy Policy | Toolbelt",
        "desc": ("How Toolbelt handles your data: what we collect, what we never collect, "
                 "and how your invoices and client details stay yours."),
        "path": "/privacy.html",
        "og_type": "website",
    },
    "terms.html": {
        "title": "Terms of Service | Toolbelt",
        "desc": "The terms that govern your use of the Toolbelt invoice and estimate app.",
        "path": "/terms.html",
        "og_type": "website",
    },
    "thanks.html": {
        "title": "Thanks | Toolbelt",
        "desc": "Thanks for getting in touch with Toolbelt. We'll get back to you shortly.",
        "path": "/thanks.html",
        "og_type": "website",
        "noindex": True,   # a confirmation page has no business in the index
    },
}

BLOG_POSTS = {
    "blog/get-paid-faster-as-contractor.html": {
        "title": "How to Get Paid Faster as a Contractor",
        "desc": ("Seven changes to how you invoice that shorten the gap between finishing "
                 "a job and seeing the money — deposits, terms, follow-ups and timing."),
        "path": "/blog/get-paid-faster-as-contractor.html",
    },
    "blog/invoicing-mistakes-contractors-make.html": {
        "title": "5 Invoicing Mistakes Contractors Make",
        "desc": ("The invoicing habits that quietly cost trades money: vague line items, "
                 "late sends, missing terms, and no deposit. And how to fix each one."),
        "path": "/blog/invoicing-mistakes-contractors-make.html",
    },
    "blog/quote-vs-invoice-when-to-use.html": {
        "title": "Quote vs Invoice: When to Use Each",
        "desc": ("A quote is a promise, an invoice is a demand. Knowing which to send — "
                 "and when — is the difference between getting paid and getting argued with."),
        "path": "/blog/quote-vs-invoice-when-to-use.html",
    },
    "blog/professional-invoice-template-guide.html": {
        "title": "The Professional Invoice Template Guide",
        "desc": ("What a contractor invoice must contain to get paid without a phone call: "
                 "every field, why it is there, and what happens when it is missing."),
        "path": "/blog/professional-invoice-template-guide.html",
    },
    "blog/contractor-tax-deductions-guide.html": {
        "title": "Contractor Tax Deductions: A Practical Guide",
        "desc": ("The deductions trades actually claim — tools, mileage, phone, home office "
                 "— and the records you need so they survive a second look."),
        "path": "/blog/contractor-tax-deductions-guide.html",
    },
}


def git_dates(rel):
    """Real dates from git history. The posts currently claim datePublished
    2025-01-20 — a year wrong, and identical across all five. Google reads
    dateModified; publishing a false one is both a lie and a wasted signal."""
    def run(args):
        try:
            return subprocess.run(["git", "-C", ROOT] + args, capture_output=True,
                                  text=True, check=True).stdout.strip()
        except Exception:
            return ""
    added = run(["log", "--diff-filter=A", "--format=%as", "-1", "--", rel])
    modified = run(["log", "--format=%as", "-1", "--", rel])
    return added or "2026-01-20", modified or added or "2026-01-20"


def ld(obj):
    return ('<script type="application/ld+json">\n'
            + json.dumps(obj, indent=2, ensure_ascii=False) + "\n</script>")


def faq_schema(src):
    """FAQPage built by PARSING THE PAGE, not by retyping the questions.

    If the FAQ copy changes and the schema is a hand-typed duplicate, the two
    drift and the schema starts describing a page that no longer exists. Reading
    it from the DOM means they cannot disagree.
    """
    qs = re.findall(r'class="faq-question"[^>]*>(.*?)</', src, re.S)
    ans = re.findall(r'class="faq-answer"[^>]*>(.*?)</div>', src, re.S)
    if not qs or len(qs) != len(ans):
        return None
    items = []
    for q, a in zip(qs, ans):
        qt = H.unescape(re.sub(r"<[^>]+>", "", q)).strip()
        at = H.unescape(re.sub(r"<[^>]+>", "", a)).strip()
        at = re.sub(r"\s+", " ", at)
        if qt and at:
            items.append({
                "@type": "Question",
                "name": qt,
                "acceptedAnswer": {"@type": "Answer", "text": at},
            })
    if not items:
        return None
    return {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": items}


def organization():
    return {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": C.SITE_NAME,
        "url": C.SITE_URL,
        "logo": {"@type": "ImageObject", "url": C.ORG_LOGO},
        "email": C.CONTACT_EMAIL,
        "sameAs": C.SAME_AS,
    }


def software_application():
    return {
        "@context": "https://schema.org",
        "@type": ["SoftwareApplication", "MobileApplication"],
        "name": C.SITE_NAME,
        "description": ("Invoice and estimate app for contractors and tradespeople. "
                        "Voice input, AI-written descriptions, and full offline use."),
        "url": C.SITE_URL,
        "downloadUrl": C.APPSTORE_URL,
        "installUrl": C.APPSTORE_URL,
        "applicationCategory": "BusinessApplication",
        "applicationSubCategory": "Invoicing",
        "operatingSystem": "iOS",
        "publisher": {"@type": "Organization", "name": C.SITE_NAME, "url": C.SITE_URL},
        "image": C.ORG_LOGO,
        # Three offers, matching the pricing section exactly. No aggregateRating:
        # we have no review data, and inventing one is the single fastest way to
        # earn a manual action.
        "offers": [
            {"@type": "Offer", "name": "Free", "price": "0", "priceCurrency": C.CURRENCY,
             "description": C.FREE_TIER_DESC,
             "category": "free"},
            {"@type": "Offer", "name": "Monthly", "price": C.PRICE_MONTHLY,
             "priceCurrency": C.CURRENCY,
             "description": "Unlimited invoices and quotes, billed monthly.",
             "category": "subscription"},
            {"@type": "Offer", "name": "Yearly", "price": C.PRICE_YEARLY,
             "priceCurrency": C.CURRENCY,
             "description": "Unlimited invoices and quotes, billed yearly.",
             "category": "subscription"},
        ],
    }


def breadcrumbs(trail):
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": name,
             "item": C.SITE_URL + path}
            for i, (name, path) in enumerate(trail)
        ],
    }


def blog_posting(meta, rel, headline):
    pub, mod = git_dates(rel)
    return {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "headline": headline,
        "description": meta["desc"],
        "datePublished": pub,
        "dateModified": mod,
        "author": {"@type": "Organization", "name": C.SITE_NAME, "url": C.SITE_URL},
        "publisher": {
            "@type": "Organization", "name": C.SITE_NAME, "url": C.SITE_URL,
            "logo": {"@type": "ImageObject", "url": C.ORG_LOGO},
        },
        "image": C.OG_IMAGE,
        "mainEntityOfPage": {"@type": "WebPage", "@id": C.SITE_URL + meta["path"]},
        "isAccessibleForFree": True,
    }


def head_block(meta, rel, src):
    url = C.SITE_URL + meta["path"]
    title = meta["title"]
    desc = meta["desc"]
    out = [BEGIN]
    out.append(f'<link rel="canonical" href="{url}">')
    if meta.get("noindex"):
        out.append('<meta name="robots" content="noindex, follow">')
    out.append(f'<meta name="description" content="{H.escape(desc, quote=True)}">')

    out.append(f'<meta property="og:type" content="{meta.get("og_type", "article")}">')
    out.append(f'<meta property="og:site_name" content="{C.SITE_NAME}">')
    out.append(f'<meta property="og:title" content="{H.escape(title, quote=True)}">')
    out.append(f'<meta property="og:description" content="{H.escape(desc, quote=True)}">')
    out.append(f'<meta property="og:url" content="{url}">')
    out.append(f'<meta property="og:image" content="{C.OG_IMAGE}">')
    out.append(f'<meta property="og:locale" content="{C.LOCALE}">')

    out.append('<meta name="twitter:card" content="summary_large_image">')
    out.append(f'<meta name="twitter:title" content="{H.escape(title, quote=True)}">')
    out.append(f'<meta name="twitter:description" content="{H.escape(desc, quote=True)}">')
    out.append(f'<meta name="twitter:image" content="{C.OG_IMAGE}">')
    if C.TWITTER_HANDLE:
        out.append(f'<meta name="twitter:site" content="{C.TWITTER_HANDLE}">')

    # --- structured data
    if rel == "index.html":
        out.append(ld(software_application()))
        out.append(ld(organization()))
        faq = faq_schema(src)
        if faq:
            out.append(ld(faq))
    elif rel == "blog/index.html":
        out.append(ld({
            "@context": "https://schema.org", "@type": "Blog",
            "name": "Toolbelt Blog", "url": C.SITE_URL + "/blog/",
            "description": meta["desc"],
            "publisher": {"@type": "Organization", "name": C.SITE_NAME, "url": C.SITE_URL},
        }))
        out.append(ld(breadcrumbs([("Home", "/"), ("Blog", "/blog/")])))
    elif rel in BLOG_POSTS:
        h1 = re.search(r"<h1[^>]*>(.*?)</h1>", src, re.S)
        headline = H.unescape(re.sub(r"<[^>]+>", "", h1.group(1))).strip() if h1 \
            else meta["title"]
        out.append(ld(blog_posting(meta, rel, headline)))
        out.append(ld(breadcrumbs([("Home", "/"), ("Blog", "/blog/"),
                                   (meta["title"], meta["path"])])))
    else:
        out.append(ld({
            "@context": "https://schema.org", "@type": "WebPage",
            "name": title, "description": desc, "url": url,
            "isPartOf": {"@type": "WebSite", "name": C.SITE_NAME, "url": C.SITE_URL},
        }))
    out.append(END)
    return "\n".join(out)


def apply_page(rel, meta, dry):
    path = os.path.join(ROOT, rel)
    if not os.path.exists(path):
        return f"  {rel}: MISSING"
    src = open(path, encoding="utf-8").read()
    original = src

    # title
    src = re.sub(r"<title>.*?</title>",
                 f"<title>{H.escape(meta['title'])}</title>", src, count=1, flags=re.S)

    # strip the metadata we now own, wherever it currently sits, so it cannot
    # exist twice: an old hand-written og:title plus a generated one is worse
    # than neither.
    # Match our own opening marker regardless of the path historically baked into
    # it. The script moved tools/ -> scripts/; pages generated before the move still
    # carry the "tools/build_seo.py" marker, and if the strip fails to match it we
    # APPEND a second block instead of replacing — duplicating the SEO block.
    begin_re = r"<!-- SEO:BEGIN \(generated by (?:tools|scripts)/build_seo\.py — do not edit by hand\) -->"
    src = re.sub(begin_re + r".*?" + re.escape(END), "", src, flags=re.S)
    src = re.sub(r'\s*<link[^>]+rel="canonical"[^>]*>', "", src)
    src = re.sub(r'\s*<meta[^>]+name="description"[^>]*>', "", src)
    src = re.sub(r'\s*<meta[^>]+property="og:[^"]*"[^>]*>', "", src)
    src = re.sub(r'\s*<meta[^>]+name="twitter:[^"]*"[^>]*>', "", src)
    src = re.sub(r'\s*<script type="application/ld\+json">.*?</script>', "", src,
                 flags=re.S)

    block = head_block(meta, rel, original)
    src = src.replace("</head>", "\n" + block + "\n</head>", 1)

    if src != original and not dry:
        open(path, "w", encoding="utf-8").write(src)

    t, d = len(meta["title"]), len(meta["desc"])
    warn = ""
    if t > 60:
        warn += f"  ⚠ title {t}>60"
    if d > 155:
        warn += f"  ⚠ desc {d}>155"
    return f"  {rel:<46} title {t:>2}  desc {d:>3}{warn}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    allpages = {**PAGES, **{k: {**v, "og_type": "article"} for k, v in BLOG_POSTS.items()}}
    for rel, meta in allpages.items():
        print(apply_page(rel, meta, a.dry_run))
    if a.dry_run:
        print("\n--dry-run: nothing written")


if __name__ == "__main__":
    main()
